#!/usr/bin/env bash

DOCKER_COMPOSE_VERSION=1.27.4

# Make sure it's root
if [ "$EUID" -ne 0 ]; then
  echo "You must run me as root!"
  exit
fi

# Ensure all existing packages and snaps are up to date
apt-get update && apt-get -y upgrade
snap refresh

# Essentials
apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common \
  openresolv \
  python3-setuptools

# Install docker (if not installed)
if ! [ -x "$(command -v docker)" ]; then
  curl -fsSL https://download.docker.com/linux/$(lsb_release -is | awk '{print tolower($0)}')/gpg | apt-key add - && \
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | awk '{print tolower($0)}') $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io 
fi

# Install docker-compose (if not installed)
if ! [ -x "$(command -v docker-compose)" ]; then
  curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
fi


